[project]
name = "live-caption"
version = "0.1.0"
description = "Realtime SST translation pipeline"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pyaudio>=0.2.14",
  "python-dotenv>=1.1.0",
  "webrtcvad>=2.0.10",
  "requests>=2.28.1",
  "openai>=1.75.0",
  "pytest>=8.3.5",
]
